### ISSUE TITLE
How to use tracking?

### ISSUE THREAD

**Issue by SuNNjek** [flathub/com.github.virtual_puppet_project.vpuppr#2]
Is there any guide on how to use tracking with the flatpak? I wanted to test it with my webcam (Logitech C170) but whenever I press the "Run tracker" button, the activity light on the webcam turns on for about 5 seconds but then turns off again and nothing happens.

When I try and run OpenSeeFace from the command line with this command:
```console
flatpak run --command=/var/data/godot/app_userdata/OpenSeeFaceGD/venv/bin/python com.github.virtual_puppet_project.vpuppr /app/bin/OpenSeeFaceFolder/OpenSeeFace/facetracker.py -c /dev/video0 -F 12 -v 0 -s 1 -P 1 --discard-after 0 --scan-every 0 --no-3d-adapt 1 --max-feature-updates 900 --ip 127.0.0.1 --port 11573
```

I get the following error message in the output over and over again:
```
Traceback (most recent call last):
  File "/app/bin/OpenSeeFaceFolder/OpenSeeFace/facetracker.py", line 256, in <module>
    faces = tracker.predict(frame)
  File "/app/bin/OpenSeeFaceFolder/OpenSeeFace/tracker.py", line 1168, in predict
    face_info.success, face_info.quaternion, face_info.euler, face_info.pnp_error, face_info.pts_3d, face_info.lms = self.estimate_depth(face_info)
  File "/app/bin/OpenSeeFaceFolder/OpenSeeFace/tracker.py", line 761, in estimate_depth
    lms = np.concatenate((face_info.lms, np.array([[face_info.eye_state[0][1], face_info.eye_state[0][2], face_info.eye_state[0][3]], [face_info.eye_state[1][1], face_info.eye_state[1][2], face_info.eye_state[1][3]]], np.float)), 0)
  File "/var/data/godot/app_userdata/OpenSeeFaceGD/venv/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'

```

**Comment by orowith2os** [comment]
I've got a repackage in the works that will (or should) fix up most issues that the current package has. The new name will be pro.vpup.vpuppr, no time set for when I'll package it.

Run the builds from upstream in a normal Linux environment, or use the EOL Beta branch, both should work with the former being more up to date.
